### ISSUE TITLE
On the Media tab, a person does not display photos in which he is marked

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#100]
Some strange problems that I can’t figure out. Some people have photos, while others do not. It seems that the issue is not in the cache - after restarting the application, the problem does not disappear. At the same time, those people who have created (and attached) the event page have photos, the photos are attached to this event, and the people in the photo are on them. Photos on the Media tab are not available for people who do not have an attached event with photos.

**Comment by impworks** [comment]
Можно по-русски. Нужно минимальное воспроизведение по шагам: создать страницу А, потом страницу Б, создать ссылку, загрузить медиа, зайти и т.д.

**Comment by Katarn** [comment]
1. Создать страницу с персоной.
2. В админке в разделе Медиа добавить новую фотографию.
3. Нажать на кнопку "Отметить", выделить человека, указать к какой странице он относится. Сохранить фотографию.
4. Перейти на страницу персоны, посмотреть раздел Медиа - там будет пусто.

Тут ещё подумалось, на фотографиях с единственным человеком (да те же портретные фотографии), должно быть не обязательно отмечать человека - рамка в таком случае будет странно восприниматься - кроме него ведь на фото больше никого нет. Возможно имеет смысл добавить поле с указанием страницы персоны к которому привязана эта фотография в целом.

**Comment by impworks** [comment]
Очередная ошибка очистки кеша. Спасибо!

По поводу особого способа отметки для портретов - доработки UI админки в целом не приоритетны, так что пока планирую, но могу принять PR.

**Comment by Katarn** [comment]
Работает, спасибо. :) Про приоритеты и PR понятно, но по .Net я, к сожалению, не специализируюсь.
