### ISSUE TITLE
Убрать ограничение на количество человек в подсказках у списков

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#104]
При больших деревьях перестают влезать в список подсказок, а каким-либо другим способом, например, просто вводом полного ФИО, их не выбрать - приложению требуется привязка к конкретной персоне по его id.

У меня приходит список из 29 человек, а показывает только 10.

**Comment by impworks** [comment]
Не понимаю. Чем бОльшую часть имени вводишь, тем меньше человек попадает в фильтр. Или у вас 29 человек с абсолютно одинаковым ФИО?

**Comment by Katarn** [comment]
Тут скорее проблема в том, что результаты поиска нерелевантные получаются. Скажем, вводишь ФИО полностью, а приоритет показа подставляется отдельно по отчествам, именам, фамилиям, но никогда не по ФИО целиком.

То есть, скажем, если ввести Иванов Иван Иванович, с сервера придёт десяток Ивановичей, десяток Иванов и десяток Ивановых - 30 человек, а именно Иванов Иван Иванович будет во втором десятке и дальше, а не на первом месте.

**Comment by impworks** [comment]
Тогда корень проблемы все же не в количестве элементов в списке, а в полохой сортировке по релевантности (на стороне Elasticsearch). Нужно подумать, что можно с этим сделать.

**Comment by impworks** [comment]
Увы, проблема с тем, что ошибка считается более релевантной чем правильное написание в Elasticsearch, не нова, и нормального решения у нее нет:
https://github.com/elastic/elasticsearch/issues/22745

Но я кое-что переделал, чтобы exact match считался более релевантным. Попробуйте, помогает ли?

**Comment by Katarn** [comment]
Вроде бы ничего не изменилось. Ввожу полное ФИО, с сервера приходит список имён, сортируется по фамилиям, в итоге мой Иванов Иван Иванович уползает вниз за пределы 10 элементов - первые 10 позиций занимают фамилии до буквы И.

**Comment by impworks** [comment]
Расширил число показываемых элементов в выпадающих списках до 50. Однако с elasticsearch нужно что-то делать...

**Comment by Katarn** [comment]
> Увы, проблема с тем, что ошибка считается более релевантной чем правильное написание в Elasticsearch, не нова, и нормального решения у нее нет:

Мне кажется, дело не в ошибке, а в том что итоговый результат имеет сортировку по фамилиям, а не релевантности.

**Comment by impworks** [comment]
Сортировка по фамилиям используется только при выборе ссылки на страницу в markdown-редакторе.

В выпадающих списках (связь, отметки на фото) сортировка должна идти по релевантности. Проблема в том, что понятие "релевантности" у Elasticsearch очень странное. Например, на моей тестовой базе даже после всех исправлений проскакивают косяки:

![image](https://user-images.githubusercontent.com/604496/69727523-c38ca480-1133-11ea-9982-fb839947f92a.png)

![image](https://user-images.githubusercontent.com/604496/69727541-cf786680-1133-11ea-9c7c-5e8d25a29ba8.png)

**Comment by Katarn** [comment]
Видно, что совпадение подсвечивается полужирным - значит как-то оно, совпадение, определяется. Может искусственно переносить такие в начало списка? Хотя, возможно, это тоже костыль.

**Comment by impworks** [comment]
Главная проблема в том, что порядок меняется и элемент перестает быть первым. Если дописать еще одну букву "Нико" - он снова вернется на первое место. Это магия Elasticsearch.

Выделение полужирным делается на клиенте - оно работает просто по вхождению подстроки, не учитывает грамматические формы и опечатки. Хорошо бы это унифицировать, чтобы клиент не занимался самодеятельностью и брал подсветку с сервера, но пока руки не доходят.
