### ISSUE TITLE
System.Exception: An error occurred while retrieving an access token.

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#108]
При авторизации (через Яндекс, как и всегда):

```
System.Exception: An error occurred while retrieving an access token.

System.Exception: An error was encountered while handling the remote login. ---> System.Exception: An error occurred while retrieving an access token.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by impworks** [comment]
Воспроизводится, причина непонятна и не в коде Bonsai. Создал issue в библиотеке, которая используется для авторизации в Яндексе:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/359

**Comment by impworks** [comment]
@Katarn а если какую-нибудь старую версию запустить, она работает или нет?

**Comment by Katarn** [comment]
Это безопасно? Новая версия не довела базу до уровня несовместимости со старой?

**Comment by impworks** [comment]
Лучше в отдельном контейнере попробовать, скопировав только настройки.

**Comment by Katarn** [comment]
Я с докером 1-й раз имею дело, но вообще, вроде как получилось запустить образ 4-дневной давности (во всяком случае другие образы удалены и не видны в ```docker image ls```), и в нём та же ошибка при авторизации.

**Comment by Katarn** [comment]
Подскажите, могу ли я манипуляцей с базой данных отвязать свой аккаунт от учётки Яндекса, перевести на логин-пароль?

**Comment by impworks** [comment]
Да, это должно быть реально - я напишу скрипт, но самое раннее - в среду.

**Comment by impworks** [comment]
```
UPDATE "public"."AspNetUsers"
SET
	"PasswordHash" = 'AQAAAAEAACcQAAAAEOKtY+Y/P0WYToOv6fhFyQKDRj8ZBPbZBNX72ilP9a9jsrk+MsX2L0Q1FVUFkbQ7SQ==',
	"SecurityStamp" = 'OFYAMDMHVW5CK5Y3W6OJIKQX4INUIZC2',
	"AuthType" = 1
WHERE
	"Email" = '<EMAIL>'
```

После этого можно будет войти под паролем `123456` и поменять его.

**Comment by Katarn** [comment]
Спасибо, наконец-то залогинился. :)
