### ISSUE TITLE
Приложение не позволяет создать страницу с таким же именем

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#113]
В частности речь о кейсе, когда создал страницу, понял что этот человек уже есть. Удалил созданную страницу, пошёл к старой, дополняешь её данными (например, дописываешь отчество). И приложение сообщает, что такая страница уже существует.

Я бы предложил при удалении страницы человека добавить галочку "Удалить целиком, включая все связи". И, возможно, ещё одну - "Включая все фотографии, где отмечен только этот человек".

**Comment by impworks** [comment]
При удалении страницы не удалялись алиасы - это баг. В новом образе должно быть исправление - можно либо восстановить старую страницу и удалить ее повторно, либо вручную удалить лишние записи из таблицы `PageAliases`.

Касательно удаления со связями и фотографиями - в текущую архитектуру эта фича не вписывается. Давать возможность безвозвратно удалить кучу данных одним нажатием - опасно, а сделать безопасно очень сложно, т.к. механизм правок не поддерживает атомарное изменение нескольких сущностей сразу.
