### ISSUE TITLE
Reduce initial startup time

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#118]
Initial startup does a lot of heavy lifting: initializing the database, populating Elasticsearch indices, etc. - and in the meanwhile the webserver does not handle any requests.

A preloader saying "Bonsai is starting up, please wait..." would be nice to have.

**Comment by DiverOfDark** [comment]
Also it would be nice if Bonsai could start up without elastic/pgsql available.

**Comment by impworks** [comment]
@DiverOfDark how is it supposed to work without a database?

**Comment by DiverOfDark** [comment]
@impworks it should show "starting..." page with possible details (i.e. - connecting to DB, connecting to elastic)

**Comment by DiverOfDark** [comment]
@impworks with you permission, I would like to try to implement this issue.
