### ISSUE TITLE
запуск через докер на localhost (run bonsai via docker on localhost)

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#119]
lets encrept не может подписать Ip адресс. А если писать через xip.ip то пишет что слишком много сертификатов.
Таким образом как мне запустить его в локальной сети, для использования опять же в этой локальной сети.

let's encrept can't sign ip address. But if i write @@YOUR_IP@@ via xip.ip, bonsai show error message. too many certificates.
like so. how to launch bonsai in local network.

**Comment by impworks** [comment]
Вижу 2 варианта:

1. Выдать компьютеру другой локальный IP, менее популярный, чтобы обойти ограничение в максимальное число сертификатов на IP.
2. Модифицировать `docker-compose.yml` так, чтобы не использовать traefik/letsencrypt вообще. В таком случае у вас не будет работать авторизация через соцсети, но все остальное будет работоспособным. Возможно, @DiverOfDark сможет с этим помочь.

**Comment by impworks** [comment]
1. Никак - letsencrypt подписывает только доменные имена. Для этого и нужен xip.io - там на каждый IP-адрес прописана одноименная DNS-запись типа “A”. Условно говоря, 192.168.1.1.xip.io резолвится в 192.168.1.1. Но этот адрес много у кого используется и, видимо, letsencrypt имеет ограничение на число одновременно выпускаемых сертификатов. Если вы поставите себе более оригинальный IP-адрес, условно говоря 1.2.3.4, то сертификат на 1.2.3.4.xip.io скорее всего сгенерируется успешно.

2. Увы, не знаю - поддержку докера реализовывал не я.

**Comment by centralhardware** [comment]
ошибку too many certificates я так и не смог повторить теперь просто выдает

` time="2020-01-11T11:19:54Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.0.19.xip.io\": unable to generate a certificate for the domains [192.168.0.19.xip.io]: acme: Error -> One or more domains had a problem:\n[192.168.0.19.xip.io] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for 192.168.0.19.xip.io, url: \n" rule="Host(`192.168.0.19.xip.io`)" routerName=bonsai@docker providerName=le.acme
`

**Comment by impworks** [comment]
@DiverOfDark давай запилим облегченную версию docker-compose, без letsencrypt/traefik/xip, чтобы был доступен только http? Это также частично поможет #120

**Comment by centralhardware** [comment]
лучше всего было бы вынести активацию данной фичи в какой нибудь флаг

**Comment by impworks** [comment]
Так `docker-compose.yml` и является конфигом с кучей таких флагов. Максимум, что можно сделать - это альтернативный preset этого конфига, как я и предлагал в предыдущем комментарии.

**Comment by DiverOfDark** [comment]
я думаю:
1) сделаем пример docker-compose.yml c self-signed certificate 
2) посмотрим как сделать чтобы он и по http и по любому адресу был доступен

**Comment by centralhardware** [comment]
большое спасибо
