### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by ion-lane** [impworks/bonsai#120]
Hello!

I was interested in your project, but unfortunately could not install it.
After installation, the site displays the message "404 page not found" on the page.
I just wanted to take a look at the functionality of Bonsai. But he spent too much time to figure out the installation of the docker. I am not a programmer and do not use it.
Do you have a demo site where i can watch a site without spending time installing it?

**Comment by impworks** [comment]
Unfortunately, no, and there are several reasons for that.

First of all, the container has to be run somewhere (actual hardware or cloud), and there are no free ways of doing so (as far as I know). Moreover, when admin access is allowed to anyone, the engine can be easily DDoS'ed and abused (uploading large files or illegal content), which will render the whole demo site unusable. Many restrictions will need to be implemented, and even then some of the problems will still stand.

Second, you will definitely need some technical expertise to run Bonsai successfully. Bonsai's main feature is that it is free and self-hosted. This comes with the downside of having to set up and manage things yourself. If that is unsurmountable, maybe some other tool (like a desktop app or a paid service) will work better for you.

As for the 404 error, make sure that you:
* Have waited at least a minute after the container has started (letsencrypt certificates take some time to generate)
* Use the `https`, not `http`

**Comment by centralhardware** [comment]
as a half measure can be a demo video with a demonstration of functionality

**Comment by centralhardware** [comment]
if demo site can work without elastic search i can host demo site

**Comment by impworks** [comment]
- [ ] Configure the host to reset every N minutes
- [ ] Password-protected default admin user
- [ ] Restrictions for default user: disable edit, password change, etc
- [ ] Limit on maximum uploaded file size

**Comment by impworks** [comment]
Demo is available here:

https://bonsai.kirillorlov.pro
