### ISSUE TITLE
нету связи брат/сестра

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#126]
может случится ситуация когда есть родственники по линии брата известного члена семьи, однако общие родители не известны

**Comment by impworks** [comment]
Это не получится сделать в таком виде, не переусложнив движок как с точки зрения внутреннего устройства, так и для пользователя.

В качестве решения предлагаю добавить пустую страницу и привязать ее в качестве родителя для обоих братьев.

**Comment by centralhardware** [comment]
а что мешает сделать так же как и сейчас, когда не известен один родитель, только в данном случае будет не известно оба родителя?

**Comment by impworks** [comment]
В первую очередь архитектурная проблема в том, что этот функционал добавляет решение для частного случая: почему только брат и сестра? А вдруг кто-то помнит другую непрямую связь: например, только дедушку? Тетю? Деверя? Что делать им? А если решать задачу в общем виде и пытаться разрешить __все__ непрямые связи, в логике вычисления связей случится комбинаторный взрыв.

Например, придется делать вычисление дополнительных связей по множеству маршрутов: например, сейчас "дядя" - это "сын родителя родителя, не являющийся твоим родителем", а будет также "брат родителя", "брат родителя брата\сестры" (если не указан собственный родитель) и так далее. Более того, можно теоретически построить целую цепочку из братьев: `A <=> B <=> C <=> D ... X`, и __каждый__ из них будет дядей для ребенка `A` - но эту связь нефиксированной длины невозможно будет выразить на существующем языке описания связей без значительной его переработки.

Кроме того, пострадают также и пользователи: искать связи в админке станет сложнее, можно запутаться. Нужно ли отдельно добавлять связь "брат", если уже есть связи "родитель-ребенок" к общему родителю?

Итого: минусы от реализации данного функционала перевешивают плюсы, особенно учитывая наличие простого решения.
