### ISSUE TITLE
нумерация страниц

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#127]
Добавить нумерация сраниц на странице "список страниц"

**Comment by impworks** [comment]
![image](https://user-images.githubusercontent.com/604496/72353305-e62f4880-36f4-11ea-9e3c-b0ebea0a8c62.png)

**Comment by centralhardware** [comment]
имелось в виду для самого списка. 
1. page1
1. page2

**Comment by impworks** [comment]
Какой в этом смысл?

**Comment by centralhardware** [comment]
Действительно спорный момент, навеянный двумя мыслями:
- нельзя численно оценить количество страниц, не смотря логи.
- запомнить позицию проще чем ФИО.

PS функция фильтрации страниц по типу была бы очень кстати.

**Comment by impworks** [comment]
Запоминать нумерацию бесполезно, потому что она в любом случае будет зависеть от текущего фильтра и сортировки. Добавили человека с фамилией на "А" - все остальные сдвинулись, и привет.

Фильтрация по типу страниц есть: выбираете один или несколько типов в самом верху и нажимаете "найти".

![image](https://user-images.githubusercontent.com/604496/72534101-4d7d0200-3887-11ea-88c7-497551868b9b.png)
