### ISSUE TITLE
Некоторые фото загружаются повернутыми на бок, что не возможно исправить

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#133]

**Comment by impworks** [comment]
Фотографии загружаются и показываются "как есть". Если она выглядит повернутой после загрузки - значит она была так снята, и ее необходимо перед загрузкой повернуть в графическом редакторе (или снимать на телефон\камеру, которая умеет делать это автоматически). Делать встроенный функционал для редактирования фотографий внутри Bonsai не планируется.

**Comment by Katarn** [comment]
Тут, возможно, имеется в виду, что приложение не использует поворот, прописанный в EXIF-тегах (он используется вьюверами чтобы не пережимать фотку после "честного" поворота и сохранения заново, а сначала декодировать оригинал и потом повернуть программно перед отображением). Возможно этот функционал включается отдельными флагами на уровне библиотеки чтения jpeg-файлов.
