### ISSUE TITLE
что такое фотосфера?

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#135]

**Comment by impworks** [comment]
https://ru.wikipedia.org/wiki/%D0%A1%D1%84%D0%B5%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%BF%D0%B0%D0%BD%D0%BE%D1%80%D0%B0%D0%BC%D0%B0

Изначально планировалось добавить возможность загрузки и просмотра таких фотографий, но из-за малой распространенности и наличия разных форматов фича была отменена.
