### ISSUE TITLE
Типы связей: брат, племянник и др.

### ISSUE THREAD

**Issue by askrinnik** [impworks/bonsai#138]
Не могу создать отношение между людьми типа брат/сестра/племянник и.т.д
Нет таких типов связей или я не туда смотрю?

**Comment by impworks** [comment]
Есть три базовых типа родственной связи: "ребенок", "родитель" и "супруг". Вы задаете только их, а остальные выводятся автоматически: например, "брат" = "другой сын родителя", "племянник" = "сын другого ребенка родителя" и так далее. Вводить вручную производные типы связей нельзя - о причинах подробно расписано в #126.
