### ISSUE TITLE
Приложение "зависает" на шаге подготовки поискового индекса

### ISSUE THREAD

**Issue by askrinnik** [impworks/bonsai#141]
Windows 10 Pro
Docker Toolbox
1. Произведена установка через docker-compose. Все контейнеры развернулись без ошибок
2. Открываю стартовую страницу в браузере
Отображается текст:
v Подготовка базы
Подготовка поискового индекса...

И в этом состоянии страница и остается даже после 10 часов ожидания

**Comment by impworks** [comment]
1. Проверить логи на предмет ошибок
2. Если в логах ничего нет - перезагрузить приложение
3. Если также не помогает - удалить и пересоздать контейнеры
4. Если все равно нет - подождать пару дней, когда мы выкатим #88 - там это все серьезно переделано и проблема больше не возникнет

**Comment by askrinnik** [comment]
1. К сожалению, не знаю, где посмотреть
2. Не помогает
3. Из трех попыток завелось один раз завелось
4. Будем ждать с нетерпением :)
