### ISSUE TITLE
404 on Rasberry PI 3

### ISSUE THREAD

**Issue by pashuk-k** [impworks/bonsai#155]
hi
Try install on that device (Rasbian OS,  Debian Buster). Do how in instruction: change email, type 192.168.*.*.xip.io, uncomment/comment some line.

All install good, but finally in browser have error 404
Try https and http, no success

**Comment by impworks** [comment]
Hello!

Please check things in the following order:
1. The containers are actually running
2. There are no errors in the log

Without particular error messages, it's not possible to determine what exactly went wrong.
