### ISSUE TITLE
Backup/Restore command for postgres, traefik containers

### ISSUE THREAD

**Issue by pashuk-k** [impworks/bonsai#156]
Hi
How create schedule command to weekly backup stored data?
Try use for postgres this:
_sudo docker exec -t **container_ID** pg_dumpall -c -U postgres | gzip > /var/data/dump_

in dump file:
_pg_dumpall: error: could not connect to database "template1": FATAL:  role "postgres" does not exist_

**Comment by impworks** [comment]
@DiverOfDark please have a look at this

**Comment by DiverOfDark** [comment]
I usually do backup by having following in crontab:

docker exec -t **container_ID** pg_dump --dbname=bonsai --username=bonsai 2>/root/backup/meguca_db.log > /root/backup/meguca_db.sql

**Comment by pashuk-k** [comment]
привет
можно ещё вопрос по данной теме?
  
>Четверг, 2 июля 2020, 16:40 +03:00 от Andrei Kurosh <notifications@github.com>:
> 
> 
>Closed  #156 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Павел Капитула

**Comment by impworks** [comment]
Можно сразу задать вопрос без предварительного разрешения )

**Comment by pashuk-k** [comment]
спасибо за команду бэкапа базы postgresql из контейнера…
а какая команда  восстановления базы postgresql в случае падения сервера?
 
также интересует команды бэкапа и восстановления  traefik  (базу медиа контента)
 
p.s. думаю Ваш проект раскрутить на кластере и раздать доступа для родни что-бы заполняли, чтобы дети потом, когда подрастут, вспомнили своих дедов и бабушек.
Спасибо вам 
>Понедельник, 6 июля 2020, 11:01 +03:00 от Andrei Kurosh <notifications@github.com>:
> 
> 
>Можно сразу задать вопрос без предварительного разрешения )
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Павел Капитула

**Comment by impworks** [comment]
В `dockerfile` указаны два образа, которые нужно бэкапить - это `database` и `images`. Про бэкап образов много написано, ищется по запросу `docker backup volume` в гугле, например:

https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes
https://blog.ssdnodes.com/blog/docker-backup-volumes/
https://medium.com/@loomchild/backup-restore-docker-named-volumes-350397b8e362

`traefik` бэкапить не надо. Это, по сути, обратный прокси-сервер, который нужен для поддержки https, и никаких данных не хранит.

**Comment by pashuk-k** [comment]
извиняюсь…. не очень силён в этой теме…
события описываются в базу данных 
database — postgresql
 
фото загружаются и привязываются к событиям
images — ???
это bonsai ? это просто папка на диске?
  
>Понедельник, 6 июля 2020, 12:15 +03:00 от Andrei Kurosh <notifications@github.com>:
> 
> 
>В dockerfile указаны два образа, которые нужно бэкапить - это database и images. Про бэкап образов много написано, ищется по запросу docker backup volume в гугле, например:
>https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes
>https://blog.ssdnodes.com/blog/docker-backup-volumes/
>https://medium.com/@loomchild/backup-restore-docker-named-volumes-350397b8e362
>traefik бэкапить не надо. Это, по сути, обратный прокси-сервер, который нужен для поддержки https, и никаких данных не хранит.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Павел Капитула
