### ISSUE TITLE
Ошибка заполнения пунктов "расшифровки" ранга

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#162]
![image](https://user-images.githubusercontent.com/26829359/88473259-f34fae80-cf45-11ea-9c4e-fb510de27f36.png)

Выделено только пункт текст, но на самой страницы питомца 

![image](https://user-images.githubusercontent.com/26829359/88473268-17ab8b00-cf46-11ea-972a-8a32dfb751eb.png)

на другой странице отмецено только фото, хотя заполнено больше полей

![image](https://user-images.githubusercontent.com/26829359/88473342-acae8400-cf46-11ea-88cc-c9b2eafd0caa.png)

**Comment by impworks** [comment]
У страницы типа "питомец" была проблема с флажком "имя" - его значение из-за копипасты совпадало со значением флажка "вид". Все остальные флажки проверил - они работают как полагается.
