### ISSUE TITLE
Неверный расчет процента ранга

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#163]
Для страниц типа человек, ранг расчитывается верно однако, на страницах типа событие наблюдается следующее поведение

![image](https://user-images.githubusercontent.com/26829359/88473435-86d5af00-cf47-11ea-84f4-77eed460fe1b.png)

![image](https://user-images.githubusercontent.com/26829359/88473438-90f7ad80-cf47-11ea-962f-a6448540f517.png)

**Comment by impworks** [comment]
Это правильное поведение.

Для разных типов страниц элементы имеют разные веса. Поскольку у события нет практически никаких дополнительных полей, кроме даты, текст описания дает 80% веса, а дата - остальные 20%. У человека же дополнительных полей много, поэтому текст дает только 30%.
