### ISSUE TITLE
[Предложение] Возможность сохранение  дерева в формате jpg,pdf и тд и тм.

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#167]
- В браузере чаще всего расматривать дерево не удобно, так как при оригинальном увеличение помещается крайне мало обьектов на экран в случае, же если отдалять маштабирование, оно меняется на всей вкладке, что так же мало удобно.
- было бы просто удобно сохранить дерево, куда нибуд чтобы показать, переслать, распечатать.

**Comment by centralhardware** [comment]
В качесте альтернативы можно добавить возможность изменения маштаба прямо в окно просмотра дерева.

**Comment by impworks** [comment]
Масштабировать можно с помощью колеса мышки, зажав Ctrl на клавиатуре. А перетаскивание должно работать по обоим осям.

Можно подумать о том, чтобы дерево рисовалось не внутри div'а основной страницы, а в iframe. Тогда его можно будет открыть как отдельную страницу. Это позволит решить сразу несколько проблем:

* Можно будет менять масштаб только дерева, не затрагивая остальные страницы и не реализуя масштабирование самостоятельно
* Можно будет использовать встроенный функционал браузера для экспорта дерева в PDF
* Можно будет использовать браузерные плагины для сохранения скриншотов дерева

**Comment by impworks** [comment]
Реализовано. Теперь на странице дерева есть две кнопки:

![image](https://user-images.githubusercontent.com/604496/180214810-9185e00a-8d6d-439c-be61-f2cac5b86083.png)

Если открыть дерево в новом окне, его можно распечатать в виде PDF (не особо удобно) или автоматически конвертировать в изображение с помощью плагина для браузера. Я использую Numbus Screenshot, справляется на ура:

https://chrome.google.com/webstore/detail/nimbus-screenshot-screen/bpconcjcammlapcogcnnelfmaeghhagj?hl=en
