### ISSUE TITLE
[Предложение] Добавление i18n

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#168]
Описание и множество issue пишутся на английском однако сам проект не имеет локализации.
Если добавить в проект техническую возможность добавления локализаций, то с помощь платформу https://crowdin.com/ (или аналогичных) можно было дать возможность добавлять нужные пользователям локализации. ОБьем тектса довльно маленький, что делает процес перевода не очень трудным, а сама проста текста дает возможность делать перевод даже людям не очень хорошо владеющих пероводом.

**Comment by impworks** [comment]
Просто перевести текст - недостаточно, потому что поддержка другого __языка__ бесполезна без поддержки другой __культуры__, а тут огромное количество особенностей:

* Формат даты (у нас `год-месяц-день`, у американцев - `месяц-день-год`)
* Имена (у нас есть отчества, у американцев - нет, зато может быть "второе имя", у японцев принято писать "фамилия имя" вместо "имя фамилия" и т.д.)
* Родственные связи (в европейских странах кузены считаются близкими родственниками, у нас же двоюродные братья имхо нет)
* Религиозные аспекты (тут даже начинать не буду, т.к. не знаю)
* Письмо справо-налево

Отдельная проблема состоит в том, что поддерживать такие вещи, нужно будет переписывать внутреннюю логику, абстрагируя ее от конкретной культуры. Это трудоемкий процесс сам по себе, и реализация новых фич также станет непредсказуемо более трудоемкой.

Поэтому я не готов поддерживать больше одного языка в текущей кодовой базе. Если у кого-то есть желание и возможность, лучше всего сделать отдельный проект посредством fork'а и локализовать его, как угодно.

Однако перевести документацию на русский - хорошая идея.
