### ISSUE TITLE
Замена для INodeServices

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#175]
Интерфейс `INodeServices` объявлен устаревшим в .NET Core 3.x и будет полностью выпилен в .NET 5. Функционал, который остается, будет поддерживать только вызов CLI-команд для SPA-фреймворков, но не будет поддерживать выполнение произвольного JS-кода, которое Bonsai использует для рендеринга фамильного древа.

https://github.com/dotnet/aspnetcore/issues/12890#issuecomment-518808555

Наиболее перспективной альтернативой мне видится подход, где мы портируем оригинальный исходник ELK с Java на C# и используем его напрямую. Преимущества данного подхода:
* Выкидывается рантайм NodeJS, остается только один .NET Core
* Нет ограничений на время выполнения скрипта, т.е. решается проблема в #164

Как это сделать - вопрос. Склоняюсь к хитрому варианту:
1. Сбилдить оригинальный пакет на Java
2. Транслировать его в сборку с помощью IKVM (https://github.com/windward-studios/ikvm8)
3. Декомпилировать сборку с помощью DNSpy

Почему так сложно?
1. Трансляторы source-to-source либо ущербные, либо платные.
2. Развитие IKVM под вопросом, сомневаюсь что он поддерживает (и будет поддерживать в будущем) актуальные версии .NET Core. Сгенерировать один раз исходник и дальше самому собирать из него библиотеку наиболее future-proof из вариантов, которые я вижу.

@DiverOfDark что думаешь?

**Comment by DiverOfDark** [comment]
Так не сработает - IKVM предлагает полноценный аналог BCL из ява-мира. Если ты уж так хочешь переписать это на C# - то стоит либо переписать руками только тот набор классов, который тебе нужен, или поискать транспиляторы.

**Comment by ForNeVeR** [comment]
Ну, по идее, можно сперва базово портировать описанным выше способом, и получить зависимость от IKVM BCL. А дальше уже вручную доработать напильником и отпилить её.

**Comment by centralhardware** [comment]
Тут под "Java" поднимается JS?

**Comment by impworks** [comment]
@centralhardware нет, под Java понимается Java. Причем тут JS?

**Comment by centralhardware** [comment]
А на каком этапе в проекте на c#, вмешивается JVM?

**Comment by impworks** [comment]
@centralhardware первое сообщение данного треда перечитайте пожалуйста

**Comment by ForNeVeR** [comment]
Возможно, там действительно недостаёт небольшого кусочка предыстории, про который не все участники разговора могут быть в курсе.

Для отрисовки дерева используется библиотека [Eclipse Layout Kernel](https://www.eclipse.org/elk/), в оригинале написанная на Java. Но, поскольку Java тащить в такое приложение показалось совершенно не с руки, был взят [порт этой библиотеки на JavaScript](https://github.com/kieler/elkjs).

Соответственно, в треде идёт разговор о том, чтобы отказаться от использования JS на сервере и выбросить JS-версию ELK, потенциально как-то создав ещё один порт оригинальной библиотеки, но уже на .NET.

**Comment by impworks** [comment]
Пока что переписать ELK на C# не представляется возможным. Я сконвертировал исходники автоматическим транслятором и потратил три полных рабочих дня на ручное исправление ошибок, но их число по-прежнему держится в районе 1500-2000. Нет возможности оценить, приближаюсь ли я к цели и заработает ли получившаяся версия корректно.

В то же время я нашел drop-in replacement для INodeServices:
https://github.com/JeringTech/Javascript.NodeJS

Пока что использую его, т.к. он решает сразу несколько проблем:
* Там можно задать таймаут для долго выполняющихся скриптов
* Он поддерживается в .NET 5
