### ISSUE TITLE
Уменьшить размер контейнера

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#178]
Если собрать Bonsai в режиме self-contained, папка весит 200 мегабайт (включая рантайм .NET Core, но без NodeJS). При этом размер контейнера равен 750 мегабайтам, а вместе с Postgres выходит вообще больше гигабайта:

![image](https://user-images.githubusercontent.com/604496/92147270-8b816300-ee23-11ea-99e7-f76518549944.png)

Откуда почти четырехкратная разница в размере? Можно ли ее как-то сократить?

**Comment by impworks** [comment]
Пока провел несколько дилетантских экспериментов (хронологически снизу вверх), сэкономил 65 мегабайт:

![image](https://user-images.githubusercontent.com/604496/92216495-09368480-ee9f-11ea-86fb-093a340be14f.png)

**Comment by centralhardware** [comment]
может стоит использовать alpine версию  mcr.microsoft.com/dotnet/core/aspnet:3.1 не знаю что выкачивается по умолчанию но судя по размеру вполне вероятно ubuntu или debain based

**Comment by DiverOfDark** [comment]
Очень много приходит с nodejs + ffmpeg. если бы можно было избавиться хоть от кого-то из них...

**Comment by impworks** [comment]
@DiverOfDark а можно поподробнее?

К сожалению, `ffmpeg` сам по себе незаменим - с его помощью Bonsai перекодирует видео в MP4 и достает из него превьюшки. Нет ли у него зависимостей, которые мы тащим "на всякий случай", но без которых на самом деле можно обойтись?

По поводу NodeJS - рано или поздно мы от него откажемся по причине #175. Я в фоне переписываю ELK с Java на C#, но идет довольно тяжело и сколько времени займет - пока не понятно.

**Comment by impworks** [comment]
Итого: 750 -> 278 mb!

![image](https://user-images.githubusercontent.com/604496/93180945-7f10da80-f740-11ea-8d40-1e5339d248c8.png)
