### ISSUE TITLE
Отказ от использования операторов json при работе с базой

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#187]
Нужно денормализовать базу: важные факты типа пола и даты рождения\смерти хранить в отдельных столбцах, а полный JSON-документ с фактами использовать только при отображении конкретной страницы.

Преимущества:
* Облегчит запросы, для которых требуется весь контекст: валидация фактов при редактировании \ создании, отображение дерева и т.д.
* Позволит в будущем мигрировать движок базы с PostgreSQL на SQLite

**Comment by centralhardware** [comment]
> Позволит в будущем мигрировать движок базы с PostgreSQL на SQLite

для миграции существующей базы данных postgres, предполагается разработка инструмента миграции?

**Comment by centralhardware** [comment]
> Облегчит запросы, для которых требуется весь контекст: валидация фактов при редактировании \ создании, отображение дерева и т.д.

Есть какие то проблемы с производительностью postgres в плане работы с json. Знаю как минимум две компании с весьма таки большой нагрузкой которые используют JSONB и не имеют с этим никаких проблем. Мы прямо сейчас отказываемся от отдельных таблиц в базе в пользу одного поля типа JSONB.

**Comment by centralhardware** [comment]
+ имею опыт использования проекта calibry-web и каждый раз когда я захожу туда, чтобы залить данные о книжках, я трачу пару дней, чтобы починить базу sqlite, Так как она в очередной раз находиться в RO, очень не хотелось бы, чтобы история повторилась

**Comment by impworks** [comment]
Проблем с производительностью нет - наоборот, задача в том, чтобы сделать деплой меньше (сейчас контейнер Postgres весит больше, чем контейнер Bonsai).

Как конкретно реализовать миграцию пока не знаю. В идеале должна быть всего одна кнопка в админке - "мигрировать БД", нажатие на которую автоматически все перенесет, после чего контейнер с Postgres можно будет отключить и удалить.

Я использую sqlite в параллельном проекте (https://github.com/impworks/isotope), где нагрузка аналогичная, и никаких проблем не возникает. Возможно, calibre просто криво работает с базой.

**Comment by centralhardware** [comment]
Но инструмент миграции будет поддерживать только одну версию схемы постгрес?

**Comment by impworks** [comment]
Нет - сначала любая версия постгреса обновляется до актуальной, потом актуальная переносится в sqlite
