### ISSUE TITLE
Создание пользователя - не помещается список "Страница"

### ISSUE THREAD

**Issue by Rudometov** [impworks/bonsai#189]
При создании нового пользователя не помещается последний список "Страница". Необходимо уменьшить список или увеличить высоту страницы.

**Comment by impworks** [comment]
@Rudometov Приложите скриншот, пожалуйста.

**Comment by Rudometov** [comment]
![bonsai_new_user](https://user-images.githubusercontent.com/2694233/111265242-da614e00-8639-11eb-8a9c-07a2d80a7815.jpg)

страница admin/users/create
