### ISSUE TITLE
Настройка главной страницы пользователя

### ISSUE THREAD

**Issue by Rudometov** [impworks/bonsai#190]
Было бы здорово иметь возможность настроить дефолтную страницу пользователя (проще, наверное, просто форвардить, куда он попадает при логине).
Например, показывать сразу свое дерево, свою страницу, календарь и тп.

**Comment by impworks** [comment]
Я поправил баг, из-за которого при авторизации по паролю не производился редирект на предыдущую страницу.

Теперь вы можете сделать гораздо проще: добавить страницу, на которую вы всегда хотите попадать, в закладки в браузере. В большинстве случаев, если вы уже авторизованы, вы сразу же попадете на нее. В остальных случаях вы вернетесь на эту же страницу после авторизации (через соцсеть или пароль). Никакой дополнительной настройки в профиле не требуется.

**Comment by Rudometov** [comment]
Спасибо. С багфиксом стало удобнее.
В идеале было бы здорово главную страницу сделать на основе виджетов, с настройкой уровня сайта или даже пользователя.
