### ISSUE TITLE
Safari система сообщаем ошибку в дате

### ISSUE THREAD

**Issue by Rudometov** [impworks/bonsai#194]
Страницы-Факты-Рождение
В браузере Safari 14.0.3 выскакивает сообщение об ошибке латы. В Chrome та же страница у того же пользователя все ок.

**Comment by Rudometov** [comment]
<img width="338" alt="Screen Shot 2021-04-23 at 16 50 27" src="https://user-images.githubusercontent.com/2694233/115939875-4ee4a380-a4a8-11eb-8ea1-2c7face7065d.png">

**Comment by impworks** [comment]
Оказывается, Safari принимает только формат `yyyy/MM/dd` в конструкторе `Date()`. Исправил, для пользователя ничего не поменяется.
