### ISSUE TITLE
логировать ошибки получения файлов из ФС 

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#197]
Произошла ситуация когда на сервер не была примантирована папка с фото для bonsai, сервер при попытки доступа к файлам выбрасывал 404 и по этой ошибки не имеется возможности понять это ошибка в базе данных или в доступе к файлу.

**Comment by impworks** [comment]
Ошибки получения конкретных файлов (404) и так логируются:

```
[INF] HTTP GET /media/foo.jpg responded 404 in 66.9011 ms
```

Теперь также добавил отдельную проверку, которая определяет отсутствие самой папки `media` или файлов в ней и пишет в лог следующее сообщение:

```
[ERR] "The 'media' directory is missing. Make sure it is mounted properly."
```
