### ISSUE TITLE
страница правки не отображает изменений

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#199]
![image](https://user-images.githubusercontent.com/26829359/119265737-eeb16080-bc11-11eb-9489-3ad248302aa9.png)

попытался выбрать json из базы по id, что был в URL, 

```sql
select * from "Changes" where 'Changes.Id' = 'b31431fc-ce09-4740-9447-c985bd2ea244'
```
но результат был пустой

**Comment by impworks** [comment]
Вы написали некорректный запрос, который по сути делает `WHERE 'a' = 'b'`, т.е. сравнивает две разные константные строки и, поскольку результат этого сравнения всегда false, не находит ни одной строки.

Чтобы найти изменения по id:

```
SELECT * FROM "Changes" WHERE "Id" = 'b31431fc-ce09-4740-9447-c985bd2ea244'
```
