### ISSUE TITLE
не работает загрузка медия 

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#203]
пробывал на: Jpg, png,pdf, docx
с reverse proxy и без

никаких ошибок в console, network в dev tools или логах контейнера

**Comment by impworks** [comment]
Без логов ничем помочь не могу.

К слову сказать, поддерживаются только изображения (jpeg, png) и видео (любые форматы, которые понимает ffmpeg).
Файлы pdf / doc / docx не поддерживаются.
