### ISSUE TITLE
Полное удаление записи

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#207]
Нужна возможность полностью удалить запись.

Для медиа-файлов при этом будет удаляться также сам контент (сейчас такая опция уже есть), для страниц - псевдонимы, для связей - обратная связь.
История изменений записи также полностью удаляется.

Функционал будет доступен только для пользователя уровня "администратор".

**Comment by centralhardware** [comment]
хочется уточнить, удаление будет физически из БД или будет выставляться признак удаления, при котором запись не будет отображаться? 
В bonsai храняться довольно таки важные данные и хотелось бы минимизировать возможность ошибочной потери данных (даже с учетом наличия бекапов)

**Comment by impworks** [comment]
@centralhardware признак удаления проставляется сейчас, чтобы оставалась история и данные можно было восстановить. Новый режим подразумевает полное удаление, как сейчас работает с медиафайлами.

Полное удаление потребует проставить галочку с подписью наподобие "удалить полностью без возможности восстановления", а сама галочка будет доступна только администратору, поэтому шанс случайного удаления будет сведен к минимуму.
