### ISSUE TITLE
Миграция с PostgreSQL на SQLite

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#215]
Сразу несколько причин:

1. Ветка PostgreSQL 9.6 больше не развивается, последняя версия вышла 11 ноября 2021.
2. "Бесшовная" пользовательских данных на более новую версию невозможна. Нельзя просто обновить версию контейнера Bonsai, чтобы он сам сделал все необходимое: пользователю пришлось бы выполнять несколько очень сложных операций вручную.
3. Контейнер PostgreSQL занимает более половины общего места, требуемого для Bonsai
4. Bonsai не зависит ни от каких специфичных для PostgreSQL возможностей. На данный момент используются JSON-операторы, но от них легко отказаться. Это запланировано в #187.
5. Упростится бэкап (база будет лежать вместе со всеми медиа-файлами)

Целевая схема миграции для пользователя будет выглядеть так:

1. Запустить новую версию Bonsai
2. Дождаться завершения миграции (при старте)
3. Убедиться, что в папке с данными появилась база (`bonsai.db`)
4. Отключить и удалить контейнер PostgreSQL

**Comment by centralhardware** [comment]
> Ветка PostgreSQL 9.6 больше не развивается, последняя версия вышла 11 ноября 2021.

можно немного раскрыть эту мысль?

**Comment by impworks** [comment]
Процесс миграции для старых пользователей описан в статье:
https://github.com/impworks/bonsai/wiki/%D0%9C%D0%B8%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-SQLite
