### ISSUE TITLE
Ссылающиеся страницы

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#216]
Предлагаю идею сделать как на Wikipedia.

Допустим, в биографии человека упоминается через wiki-разметку другой человек. Можно было бы переходить на его страницу и почитать, какое участие в жизни первого принимал второй.

**Comment by impworks** [comment]
Хорошая идея и относительно несложно реализуется. Сделаю в ближайшее свободное время

**Comment by impworks** [comment]
@Katarn правильно ли я понял, что на каждой странице должна появиться четвертая вкладка "ссылки", на которой списком обозначены страницы, ссылающиеся на данную из текста?

**Comment by Katarn** [comment]
Да, всё так.

**Comment by impworks** [comment]
Добавилась дополнительная вкладка:
![image](https://user-images.githubusercontent.com/604496/180241968-fd953939-df28-4806-8796-7354db82092b.png)

**Comment by Katarn** [comment]
Круто, спасибо!
