### ISSUE TITLE
Опция отключения чёрной ленты в дереве

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#217]
Предлагаю такую опцию в настройках.
Когда ветвей дерева с чёрной лентой много, дерево выглядит очень мрачно.

**Comment by impworks** [comment]
Ок, реализуемо.

**Comment by impworks** [comment]
![image](https://user-images.githubusercontent.com/604496/148185351-97cc79e3-7be8-4419-9b8e-c7dd8037fe06.png)
