### ISSUE TITLE
SaaS

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#219]
Может имеет все таки смысл развивать продукт в сторону Saas. Если присутствует крайнее желание упращение жизни конечным пользователям. Так как именно распространение продукта по модели SaaS максимально полно и адекватно позволит упростить жизнь.
Превентивное оказуаливание self hosted по довольно спорным причинам, не кажется грамотным решением. В частности:

> Ветка PostgreSQL 9.6 больше не развивается, последняя версия вышла 11 ноября 2021.

https://github.com/impworks/bonsai/blob/master/docker-compose.yml#L70 как видно из данного примера кода у всех новых пользователей за последний (вроде) год уже не будет базы 9,8 версии. Скажу больше у любого адекватного человека, устанавливающий bonsai после выхода postgres 10 не будет базы на 9,8. Я лично начал с postgres 12, потом перешел на 13 версию. 
Каких вообще макаром, прекращение подддержки старой версии postgres могло стать поводом уййти вообще с postgres? Когда закончиться поддержка window 10 вы тут же уйдете на линукс?

> "Бесшовная" пользовательских данных на более новую версию невозможна. Нельзя просто обновить версию контейнера Bonsai, чтобы он сам сделал все необходимое: пользователю пришлось бы выполнять несколько очень сложных операций вручную.

А установить сервер, обеспечить его функционирование, установить докер, разобраться с reverse proxy, это как нажать пару кнопок? Если человек занимается self hosted Это потребует от него усилий, больших, усилий еще до того, как он начнет установку bonsai.

> Контейнер PostgreSQL занимает более половины общего места, требуемого для Bonsai

а оставщуюся половину места занимает runtime .NET.  Это никого не смущает. Много места это когда вы хотите скачать big blue button и вам предлагают качать три гагабайта.

> Bonsai не зависит ни от каких специфичных для PostgreSQL возможностей. На данный момент используются JSON-операторы, но от них легко отказаться. Это запланировано в Отказ от использования операторов json при работе с базой #187.

А почему бы тогда вообще не переписать проект на ORM и дать пользователям выбирать базу самим и закрыть тему с надо ли нам мигрировать на sqlite3 или нет, это.  С ORM это будет всецело проблема пользователя. 

> Упростится бэкап (база будет лежать вместе со всеми медиа-файлами)

есть два типа людей кто делает бекапы и кто еще не делает. Есть два типа людей кто делает бекапы и кто проверяет возможность их востанволения, есть два типа людей кто испольует 3+2+1 стратегию резервирования данны и кто еще не испольует. Мысль думаю понятно. может быть и упростит, но илюзия сохранности данных никуда не денется. Если надо прямо упростить то почему бы опять же не сделать автоматический бекап на google drive. Если вы уж делаете из конечных пользователей людей не способных обновить postgres почему вы уверены что они смогут выполнят адекватный бекап sqlite файла?

Если уж мигрировать на embeded DBMS, то где хотя бы попытка сравнению аналогов. Я обсуждал ситуацию в чате про уход с постгреса в контексте bonsai, так там сходу предложили firebird, которая, о чудо, by desing спроектирована так, что в общем то даже спора уходить не уходить не возникло бы. 

Есть милион причин отказаться от postgres, однако не было озвучино ни одной существеной, которую ожидаешь услышать, когда тебе говорят отказ от postgres.

**Comment by impworks** [comment]
https://github.com/impworks/bonsai/issues/187#issuecomment-954863536

Вот это прочитайте, пожалуйста, внимательно. Там написано совершенно не то, с чем вы так яростно пытаетесь спорить.
