### ISSUE TITLE
Сохранять имя фотографии при импорте

### ISSUE THREAD

**Issue by zlsl** [impworks/bonsai#225]
Предлагаю при загрузке фотографий ставить имя по-умолчанию из имени файла.
Это важно, когда в старых фотографиях нет метаинформации ни о дате, ни о месте съемки и в домашних архивах удобно в имя файла заносить дату, описание и прочее.

**Comment by impworks** [comment]
Сделал. Теперь при загрузке есть маленькая галочка, по умолчанию включена - при желании можно отключить и вернуть старое поведение с пустыми названиями:

![image](https://user-images.githubusercontent.com/604496/179368153-5338d050-f983-43fd-95f9-625aae3b9fc2.png)

Из названия файла вырезаются символы, которые не являются буквами или цифрами.
