### ISSUE TITLE
Вопрос: где посмотреть всё дерево?

### ISSUE THREAD

**Issue by seventhsite** [impworks/bonsai#228]
Привет!
Выглядит классно! А где можно увидеть, собственно, всё древо? На демо нашёл визуализацию только если зайти в конкретного человека.

**Comment by impworks** [comment]
Добрый день!
Со страницы человека видно весь связанный с ним граф вверх и вниз.
Если у вас в базе есть несколько не связанных между собой подграфов (например, две независимые семьи) - увы, посмотреть их на одной схеме на данный момент нельзя.
