### ISSUE TITLE
Управление-> страницы -> поиск не работает

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#243]
Даже если скопировать из заголовка страницы, все равно выдает, что ничего не найдено

**Comment by impworks** [comment]
На демо-стенде работает:
https://bonsai.kirillorlov.pro/admin/pages?OrderBy=Title&OrderDescending=False&SearchQuery=%D0%B8%D0%B2%D0%B0%D0%BD

Что именно вы вводите?

**Comment by centralhardware** [comment]
походу дело в colation. :(
