### ISSUE TITLE
В разделе жена отображается ссылка на одну жену, несмотря что связи две

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#244]
PS вообще тут было бы удобно указать в какой очередности были эти браки

**Comment by impworks** [comment]
Должны отображаться все, в порядке от самого нового брака до самого старого, если у связей указаны диапазоны дат. Если у вас не так - попробуйте воспроизвести на новой странице и опишите шаги, что конкретно вы делали. Если не воспроизведется на новой - смотрите внимательно на связи, возможно что-то забыли указать.

Также: связи, относящиеся к разным группам, наверное стоит визуально отчеркнуть друг от друга

**Comment by centralhardware** [comment]
пересоздал связи, проставил даты и все равно отображается только одна жена и при этом не хронологически последняя

**Comment by centralhardware** [comment]
на самом дереве все отображается правильно

**Comment by impworks** [comment]
В админке:
![image](https://github.com/impworks/bonsai/assets/604496/257e0b45-de40-4b7d-a9c0-239d25b25a19)

В карточке:
![image](https://github.com/impworks/bonsai/assets/604496/89d83fef-8ce6-4418-a33d-4e2ef56da5da)

Без деталей я не могу понять, что вы ожидаете и что получаете

**Comment by centralhardware** [comment]
ожидаю увидеть на втором скрине две ссылке, сейчас у меня получается увидеть только ссылку на хронологически раннию связь
