### ISSUE TITLE
Отдельное поле девичья фамилия для женских страниц

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#247]

**Comment by impworks** [comment]
Уже можно с помощью более общего механизма - для каждой страницы разрешено указывать сколько угодно имен с опциональными диапазонами дат. Помимо описанного вами покрывает смену имен и фамилий для обоих полов, псевдонимы и прочее. Если имя и отчество не менялись, то будут показаны только фамилии:

![image](https://github.com/impworks/bonsai/assets/604496/fe21818e-7b89-4f86-ad18-2a0ee47fa17c)
