### ISSUE TITLE
Добавить поле гражданство

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#248]
Изначально о таком даже и не думал, но в родослоной появился человек родившийся в другой стране и сразу назрел вопрос об гражданстве

**Comment by centralhardware** [comment]
В целом из вытекает: страна проживания, наличие ВНЖ/ПМЖ

**Comment by impworks** [comment]
Предметная область очень обширная, интерфейсом для фактов ее не обхватишь как следует. ВНЖ можно получить (дата, причина?), можно утратить (также дата и причина, список допустимых причин другой), у ВНЖ также есть тип (в каждой стране список свой), один тип ВНЖ можно превратить в другой... Получается, что интерфейс будет либо ограниченным, либо настолько широким, что теряется смысл от структурного хранения данных.

Итого: эту информацию лучше писать в тексте статьи в свободном виде.
