### ISSUE TITLE
Добавить возможность добавлять страницы в социальных сетях

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#250]
В идеале бы интегрироваться с web archive, но не знаю насколько это вообще возможно для социальных сетей

**Comment by impworks** [comment]
Добавил возможность в списке фактов указывать ссылки на несколько известных типов соцсетей - facebook, twitter, vk, одноклассники, youtube и т.д., которые будут отображаться на странице в виде иконок со ссылками.

"Интеграция с web archive" не планируется, что бы это ни значило.
