### ISSUE TITLE
Уведомление об событиях

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#251]
День родения, годовщина.
транспорт:
- email
- telegram (реализуется одним post запросом
- уведомления в браузере (нужен https)

**Comment by impworks** [comment]
Встроенную поддержку всех этих видов транспорта делать нерезонно, поскольку это огромный фронт работы и поддержки.

Вместо этого можно выставить наружу обычный HTTP API, возвращающий список событий и (возможно) другие данные. Пользователь сможет использовать любую платформу автоматизации (IFTTT, Zapier, ...) и мышкой в визуальном редакторе накидать в ней workflow вида "раз в сутки брать данные отсюда и отправлять туда", используя сотни готовых плагинов для любых видов транспорта. Или даже написать свой скрипт на любом известном языке. Можно будет также сделать инструкцию в wiki с примерами того, как это настраивается.

Для работы над API заведу отдельную задачу.
