### ISSUE TITLE
Возможность изменения связи

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#254]
Возможно не нашел как это делать, но было бы удобно менять диапазон дат в связи без необходимости ее пересоздавать

**Comment by impworks** [comment]
Связь редактируется при нажатии на тип. Сделать другой столбец ссылкой не получится, потому что тогда будет казаться, что это ссылка не на связь, а на страницу.

P.S. В следующий раз, пожалуйста, перед созданием тикета потратьте немного усилий на самостоятельное изучение и четкое формулирование мысли - если баг то "что делаю, что ожидаю, что получаю", если фича - то "что должно быть, почему это важно" и т.д.. В текущем виде это зачастую больше похоже на поток сознания, который сложно разбирать
