### ISSUE TITLE
readme: сломанные ссылки

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#256]
В разделе https://github.com/impworks/bonsai?tab=readme-ov-file#%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BD%D0%B0-windows

2. Установите [PostgreSQL server 9.6](https://www.openscg.com/bigsql/postgresql/installers.jsp/)
3. Скачайте [shared-сборку ffmpeg](https://ffmpeg.zeranoe.com/builds/) для вашей операционной системы и извлеките данные в папку External/ffmpeg в корне проекта (необходимы исполняемые файлы ffmpeg и ffprobe).

Ссылки ведут на неодоступные в данный момент ресурсы (www.openscg.com, ffmpeg.zeranoe.com). 
PS: + актуальная версия Postgres сейчас 15

**Comment by impworks** [comment]
Ссылки обновил.

Версия по-прежнему указана 9.6. Обновить контейнер БД до новой версии автоматически нельзя, от пользователя будет требоваться мигрировать данные вручную, что нетривиально, поэтому я не планирую обновлять версию PostgreSQL. Поддержка SQLite в дополнение к PostgreSQL должна решить эту проблему, но это сильно усложнит поддержку, поэтому руки пока не доходят.

**Comment by centralhardware** [comment]
Вероятнее всего пользоваться инструкцией по установе postgres будет человек у которого в текущей момент нету базы данных (которую необходимо было обновлять), соответственно в этом кейсе пользователю будет более полезно установть наиболее новую версию postgres
