### ISSUE TITLE
GitHub workflow для создания Docker image приложения

### ISSUE THREAD

**Issue by askrinnik** [impworks/bonsai#258]
Было бы удобно иметь такой workflow и запускать его либо по merge событию (для nightly builds) либо вручную для создания релизных сборок.
Я постараюсь сам в ближайшее месяц выделить время и сделать такую фичу. Ну и соответственно через Fork и PR предложить изменения

**Comment by impworks** [comment]
Так `latest`-образ сейчас и так собирается через Github Actions. Или вы про что-то другое?

https://github.com/impworks/bonsai/blob/master/.github/workflows/docker.yml

**Comment by askrinnik** [comment]
Странно, поиск в DockerHub его не находит
Да и наверное неплохо бы его увидеть и в GitHub. В разделе packages репозитория

**Comment by askrinnik** [comment]
Ну ок, тогда можно закрывать. Хотя конечно альтернатива в шеРги тоже была бы уместна :)

**Comment by impworks** [comment]
А, теперь кажется понял, про что вы. Попробую объяснить, чтобы все встало на свои места.

Github Actions выполняет некоторое действие при коммите в `master`, т.е. собирает docker-образ и пушит его в Docker Hub под тегом `latest`. Когда выходит (в прошлом выходил) крупный релиз стабильной версии, я самостоятельно добавлял теги (v3, v4, v5).

Отдельную фичу Releases в репозитории непонятно как использовать - там нужно загрузить файл, а образы docker не распространяются в архивах, они качаются самим docker из репозитория.

Теоретически можно было бы собирать версию при создании PR и гонять на ней какие-то тесты... но тестов в проекте нет.
