### ISSUE TITLE
При редактировании существующих страниц возникают дубли при поиске

### ISSUE THREAD

**Issue by JeyDim** [impworks/bonsai#280]
При редактировании существующей страницы дублируется документ люцины

В экшене `PagesController.Update(PageEditorVM vm, string tab)` имеется строчка `await _search.AddPageAsync(page);`

Результат изменения, например, описания:
![изображение](https://github.com/impworks/bonsai/assets/29121960/6970b479-4752-4b39-bf6d-348db2fe366a)

**Comment by impworks** [comment]
Спасибо, поправил!
