### ISSUE TITLE
Некорректное отображение фамилий некоторых людей на графе

### ISSUE THREAD

**Issue by redmanmale** [impworks/bonsai#283]
* для мужчин с одной фамилией в данных на графе отображаются две, вторая в скобках, будто он её менял
* для женщины в браке, с двумя фамилиями в данных, на графе отображаются две одинаковых, будто она её не меняла

v6.0, docker, postresql

**Comment by centralhardware** [comment]
Проверил у себя,  да фамилия дублируется, но только у пары человек из где то 90 на всем графе

**Comment by impworks** [comment]
Ошибка возникала на недавно измененных страницах. Чтобы убрать, необходимо обновиться до последней версии и пересохранить некорректно отображающиеся страницы.

**Comment by redmanmale** [comment]
проверил, исправлено

спасибо за оперативный фикс!
