### ISSUE TITLE
Поддержка неполных дат

### ISSUE THREAD

**Issue by redmanmale** [impworks/bonsai#284]
Часто бывает, что дата рождения/смерти известна не точно, а только год или год и месяц. Или даже диапазон.
Только год сейчас задать можно, остальное — нет.

Я видел #7, но может простейшие сценарии можно настроить и в текущей реализации пикера.

**Comment by impworks** [comment]
Неточную дату можно вписать руками в различных форматах, например:

`195?` - 1950-е
`1987` или `1987.??.??`
`1991.02.??` - февраль 1991

Существующий UI-пикер такие форматы не поддерживает, чтобы поддерживал придется переписать его целиком вручную.

Указание более гибких диапазонов, имхо, слишком затратно для того узкого кейса, который оно покрывает, поэтому делать не планирую.
