### ISSUE TITLE
Возможность при просмотре дерева скрывать людей на основание фильтра (например по фамилии)

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#293]

**Comment by centralhardware** [comment]
сюда же можно отнести возможность поиск человека на дереве

**Comment by impworks** [comment]
Скрывать нереализуемо, искать можно встроенными средствами браузера через Ctrl+F.

**Comment by centralhardware** [comment]
@impworks  в теории возможно было бы сделать новое поддерево, но которое бы строилось по принципу: в поддерево включаются все страницы имеющие одну фамилию + их ближайшие родственники (дети, супруг). Поясню кейс: как правило генеалогическое дерево строиться от человека одного человека, который это дерево и создал. и так как у него два родителя мы сразу получаем два поддерева, который формально являются частью одного дерева, но единственная связь данных поддеревьев (одно для матери, одно для отца) это сам автор, поэтому, если ты работаешь с наполнением ветви отца, тебе не важные люди на стороне матери и ты в них не будешь смотреть или править, то же самое если мы добавляем данные в ветвь матери. Именно это побудило меня создать данное issue
