### ISSUE TITLE
Невозможно отличить страницы, если одинаковое имя фамилия отчество, при создание связи

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#295]
Как решение возможно для таких страниц добавлять дату создания или какой либо уникальный ИД чтобы можно было выбрать нужную страницу

**Comment by impworks** [comment]
Можно скриншот? По идее то, о чем вы говорите, не должно быть возможно, или я вас не понимаю.

В форме создания связи в выпадающих списках используется не ФИО из фактов (которое может совпадать), а заголовок страницы, который должен быть уникальным, иначе вы просто не сможете ее сохранить. Если у вас есть прямо полные тезки, вам еще на этапе создания страницы придется придумать подходящий вам способ как их различать (например, дописывать год рождения).

**Comment by centralhardware** [comment]
да действительно, нельзя создать две страницы с одним и тем же названием. Причина возникновения моей ситуации был пробел в конце названия, соответственно названия получаются разные, но в выпадающем меню они визуально будут не отличимы

**Comment by impworks** [comment]
Я не буду это делать по двум причинам:
1. Проблема не критичная: полные тезки в семье - относительно редкая ситуация
2. Визуальную неотличимость двух строк _крайне_ сложно реализовать технически в общем случае (помимо пробелов в конце могут быть разные типы пробелов в середине, разные тире, латинские символы похожие на русские и прочая юникодная чертовщина), а делать кое-как для частного особого смысла нет
