### ISSUE TITLE
Добавить способ быстрого открытия дерева

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#296]
Единственный способ посмотреть дерево это зайти на страницу свою или чужую и открыть вкладку дерево, но по моему опыту мне абсолютно не важно открывать дерево от лица какого либо человека, хотя это и будет удобно если нужно просматривать subtrees. Я вижу следующие варианты, которые могут сделать открытие дерева более удобным:
- добавить новый пункт "дерево" в меню открывающееся по клику на имя пользователя
- добавить на главную страницу ссылку для быстрого перехода на дерево
- встроить дерево напрямую на главную страницу

PS: единственное, я не знаю как в данном случае разруливать ситуацию когда у нас больше одного поддерева

**Comment by impworks** [comment]
Чтобы перечислить деревья, у них должны быть осмысленные уникальные названия, которые также не теряют актуальности по мере добавления-удаления страниц. Я не вижу способа сделать это как-то иначе, чем уже сделано сейчас, исходя из текущей страницы.

В вашем случае, имхо, самым простым (и уже рабочим) вариантом будет сохранить ссылку на конкретное дерево в закладки браузера.
