### ISSUE TITLE
Добавить возможность добавлять больше одного фото человека

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#297]
Мотивация: с течением времени человек претерпевает изменения, и если фото взрослого человека в целом имеет довольно высокий срок актуальности, то фото ребенка (в особенности младенцев) устаривает в течение нескольких лет. Поэтому было бы закономерно, добавлять новые фото человека по мере его взросления, при этом во всех местах где показывается фотография выводиться будет хронологически самая старшая. Но пользователи получат возможность увидеть как менялся человек с течением времени

**Comment by impworks** [comment]
Теперь работает так: если при создании или редактировании страницы мы выбрали для нее заглавное фото, у которого нет ни одного тега, то добавляется тег, ссылающийся на эту страницу. Таким образом, все эти фото будет показываться во вкладке "медиа" на странице и не потеряются.
