### ISSUE TITLE
Указание факта смерти человека без каких либо данных об смерти

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#298]
В случае моего дерева практически всегда неизвестно никаких данных об смерти человека кроме того, что его точно нету в живых. В результате в самом дереве у человека нету ленточки. В итоге, для случая человек без ленты, существует два варианта: он еще жив и мы не знаем его дату смерти. Было бы удобно указать явно, что человек умер без заполнения каких либо полей об смерти. Тогда все живые будут без ленточек, а все мертвые с ними.
PS еще я попробовал добавить текст "тест"  в поле "причина смерти" как обходной путь, но  это не привело к появлению ленточки

**Comment by impworks** [comment]
Факт указывается галочкой "дата неизвестна":

![image](https://github.com/impworks/bonsai/assets/604496/8e8d6ca7-08dc-46ed-9a9f-a9c67ca652ec)

После этого:
* В профиле показывается факт смерти без указания даты
* В дереве появляется черная полоска, если полоски глобально не отключены настройками

**Comment by centralhardware** [comment]
а по поводу остальных полей? если заполнена причина смерти но не заполнена дата смерти, то это довольно однозначно говорит, что человек все таки умер уже
