### ISSUE TITLE
Добавить бы масштабирование дерева

### ISSUE THREAD

**Issue by dspost** [impworks/bonsai#300]

**Comment by centralhardware** [comment]
Масштаб страницы в самом браузере можно менять

**Comment by impworks** [comment]
Если вам нужно получить дерево в масштабе, самый лучший вариант - открыть его в отдельном окне (по кнопке) и увеличить с помощью масштабирования браузера. Отдельных кнопок в приложении для этого не будет.

**Comment by dspost** [comment]
Спасибо за ответ. Все же интуитивно крутим колесико мыши... Масштабирование браузера - это другое :-)
