### ISSUE TITLE
Путаница в связях между людьми в дереве

### ISSUE THREAD

**Issue by John710** [impworks/bonsai#309]
Когда было немного людей, все отображалось корректно, но когда добавил уже 64 человека, появились вот такие коллизии.
![2024-12-01_08-25-05](https://github.com/user-attachments/assets/6a08ab43-146a-4502-a3d7-c1e066ca33ac)
Разобраться что куда и к кому, без рюмки, крайне тяжело. Есть ли возможность переработать построение дерева?
Помимо этого изза большого количества людей, некоторых супугов раскидало по разным сторонам дерева, так явно быть не должно, супруги должны быть вместе на дереве.

Так же можно рассмотреть возможность добавить вот такое отображение линий, визуально линия обрезается и после карточки продолжается, так сделано в myheritage.
![2024-12-01_08-24-07](https://github.com/user-attachments/assets/7c89c4a4-483f-4f76-8773-1a58cdb98df9)

**Comment by centralhardware** [comment]
Насколько понимаю эта задача не решаема алгоритмически. Так что что есть то есть. Мне видится только один вариант: дать возможность пользователю двигать карточки на дереве вручную

**Comment by John710** [comment]
> Насколько понимаю эта задача не решаема алгоритмически.

Я тут не соглашусь. В MyHeritage персон гораздо больше, а подобных проблем ни одной, хотя так же соединено линиями. Там логика построения другая, супруги жестко рядом друг с другом, дети строго снизу от них, таким образом семьи наглядно видно, и уже соединения идут между семьями(ветками дерева).

**Comment by centralhardware** [comment]
@impworks выше я имел в виду возможность редактировать только отображение без сохранения каких- либо изменений в базу
