### ISSUE TITLE
Девичья фамилия

### ISSUE THREAD

**Issue by John710** [impworks/bonsai#310]
Есть ли возможность добавить логику отображения девичьей фамилии?
То есть указываем текущую фамилию женщины на ее странице, а в карточке добавляется девичья фамилия(в скобках), присвоенная от родителей. 
Да, это можно в ручную указывать, но по мне так удобная мелочь.

**Comment by centralhardware** [comment]
Можно добавить сколько угодно смен ФИО и выбрать дату когда это было. Первая фамилия будет отображаться в скобочках как девичья

**Comment by John710** [comment]
> Можно добавить сколько угодно смен ФИО и выбрать дату когда это было. Первая фамилия будет отображаться в скобочках как девичья

Понял, спасибо за пояснение, этот функционал еще проверял, на данный момент пока еще не всех людей перенес, уже потом буду заполнять данные к ним. 
Но опять же здесь это реализовано через ручное заполнение, как будто руками рисую дерево, все же программа "компьютерная" и хочется видеть какие то приемущества перед аналовыми.
Мне кажется это должно автоматически отображаться через связи "Супруг" и "Родитель\Ребенок". Изначально женщине вводим ее девичью фамилию и если она в данный момент в браке, то ставится девичья фамилия рядом в скобки, а фамилия мужа как основная, и наоборот.

**Comment by centralhardware** [comment]
Фамилию можно не менять в браке а можно и поменять без брака ¯\_(ツ)_/¯

**Comment by John710** [comment]
> Фамилию можно не менять в браке а можно и поменять без брака ¯_(ツ)_/¯

Этих женщин не моймешь)

**Comment by impworks** [comment]
Bonsai не может угадать фамилию за вас, потому что тут может быть масса сценариев развития событий:

1. Жена берет фамилию мужа, оставляет свою, берет двойную
2. Муж берет фамилию жены (такое тоже бывает)
3. Жена меняет или не меняет фамилию обратно при разводе
4. Человек берет себе псевдоним
5. Человек берет себе новое имя при получении гражданства другой страны

Приложить немного усилий лучше, чем иметь ошибочно угаданные данные

**Comment by centralhardware** [comment]
Последний сценарий очень интересный, человек не всегда с получением нового гражданства выходит из предыдущего и тогда у него два ФИО одновременно существуют
