### ISSUE TITLE
Name autocomplete in text editor

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#60]
Currently if you want to reference one page from another, you have to either open the page search modal window, or type the entire link markdown code letter-by-letter.

It would be useful to add an autocomplete dropdown after typing a @ symbol, much like Github does:

![image](https://user-images.githubusercontent.com/604496/52788196-434bf580-3071-11e9-8efd-3784b23ef5e6.png)

The SimpleMDE editor is based on CodeMirror editor component, which [supports](https://codemirror.net/demo/complete.html) autocomplete.

**Comment by impworks** [comment]
Apparently, SimpleMDE authors did not keep compatibility with existing CodeMirror plugins (which rely on a global variable named `CodeMirror`):

https://github.com/sparksuite/simplemde-markdown-editor/issues/418

The solution will require either recreating the `show-hint` plugin in a custom manner, or forking SimpleMDE to bake it in.

**Comment by wwsalmon** [comment]
@impworks stumbled upon this while trying to implement something similar with SimpleMDE. Did you end up implementing this functionality? Did you make a custom fork of SimpleMDE for it?

**Comment by impworks** [comment]
@wwsalmon hey! I tried a few approaches the one that worked best for _this particular project's case_ was to create a makeshift pop-up using jQuery and a lot of keydown handlers. I haven't completed it yet though due to lack of free time, but I intend to finish it somewhere around April.

**Comment by wwsalmon** [comment]
@impworks gotcha! what were some other approaches that you tried?

**Comment by impworks** [comment]
@wwsalmon well, basically I tried to:

1. Make `show-hint` plugin work with current build of SimpleMDE (appears impossible)
2. Rebuild SimpleMDE with extra plugins
3. Bind SimpleMDE and some other pop-up library together

The catch here is that Bonsai is not a typical web app. It is supposed to store family history data for hundreds (!) of years and be rewritten from scratch every 10-20 years using modern approaches and technologies. So the rule of thumb is to prefer components that "work" out of the box, and solutions that require as little specific knowledge as possible.

**Comment by impworks** [comment]
![image](https://user-images.githubusercontent.com/604496/124249486-9b91ce00-db2c-11eb-8a83-c35edd5b0be0.png)
