### ISSUE TITLE
Upgrade to .NET Core 3

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#85]
The project should be migrated to .NET Core 3.0 and all corresponding technologies: ASP.NET Core 3, EF Core 3, etc.

@DiverOfDark would that require any changes to the docker config?

**Comment by DiverOfDark** [comment]
Yes, it would.
You should update 
FROM: strings and update references to .net core images. They were moved to another repository from docker.central to mcr.microsoft.com so for builder it should look smth like:

FROM mcr.microsoft.com/dotnet/core/sdk:3.0

Not sure about runner image though, need a little bit of testing.

**Comment by impworks** [comment]
EF Core 3 has several breaking changes and a lot of reported, some of which might affect Bonsai.
Probably a good idea to wait until 3.1 is released.

**Comment by impworks** [comment]
Implemented in PR #128.

This is now in `master` branch, so Docker tag `latest` has this updates. For a stable version, use the `3.0` tag.
