### ISSUE TITLE
Remove or optional Elasticsearch dependency

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#88]
Hello! Thanks for the great app. Have you tried make searching of the names in the database as indicated in this comment? https://habr.com/ru/post/438622/#comment_19743164 Unlinking from Elasticsearch will be very useful, as it requires to rent additional capacity from the host. And on Raspberry Pi past generations does not start due to lack of RAM.

**Comment by impworks** [comment]
Hello! I agree that Elasticsearch dependency is a heavy one and removing it would benefit the project. However, I haven't had enough time to work on this myself. A pull request would be welcome.

**Comment by Katarn** [comment]
Привет. Я правильно понимаю, что ES уже выпилен, но функциональность приложения нисколько не изменилась?

**Comment by impworks** [comment]
Да, все верно.

Elasticsearch является, по сути, оберткой над библиотекой Lucene с кучей дополнительного функционала. Теперь мы используем порт Lucene под .NET напрямую. Таким образом, поиск никуда не делся, но наоборот - серьезно улучшился:

* Размер приложения и требуемый объем памяти значительно уменьшились: больше не нужен Java Runtime и весь Elastic
* Исправлен баг с сортировкой результатов поиска по релевантности
* Исправлен баг с пропаданием подсказок по мере набора текста
* В подсказках более точно подсвечивается совпавший текст
* Полнотекстовый индекс строится по актуальным данным при старте приложения, и не может "рассинхронизироваться" при восстановлении БД

**Comment by Katarn** [comment]
Крутяк, спасибо! Пока что несколько выпал из процесса составления дерева. Потестирую позже, как дела разгребу.

**Comment by Katarn** [comment]
Проверил - вроде всё круто. На первый взгляд качество поиска не пострадало. Но зато разница в объёме занимаемой памяти очевидна.
