### ISSUE TITLE
Search improvement

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#9]
Search results are not always sorted in order of relevance. A thorough examination of the Elasticsearch config is desired.

**Comment by impworks** [comment]
Seems to be working fine for actual data. Closing this for now.

**Comment by impworks** [comment]
Discussion in #104 revealed that the search, in fact, doesn't work fine. Some of the found issues are:

* Exact match can be outranked by other, seemingly unrelated matches
* Sometimes match fails/succeeds/fails during autocomplete as letters are added: e.g. for `foobar` in the database, `fo` - OK, `foo` - nothing found, `foob` - OK again, and so on.

Options to consider:

* Perform a thorough examination of the indices and search queries (unfortunately I have no idea how it works at all in the first place, its intricacies are way too convoluted and my experience is shallow, may be worth hiring someone)
* Upgrade Elasticsearch to 7.x, use built-in hunspell dictionaries instead of `russian_morphology` and see if it works better
* Replace Elasticsearch altogether with Postgresql search: https://habr.com/ru/post/438622/#comment_19743164 (which is especially cool since elasticsearch + java are huge dependencies, dropping them without compromising search quality would be awesome)

**Comment by DiverOfDark** [comment]
I am keen to investigate other solutions, i.e. Lucene.NET, but for that I need some test data, ideally unit-tests with samples that should work. You already have seed data, so it probably should not be that hard to implement 'em.

**Comment by impworks** [comment]
Great, will do that next week.
