### ISSUE TITLE
Avatars for wiki pages do not appear immediately

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#92]
I did not understand when they should appear. I upload an avatar on the person’s page, click on the Preview button - there is an avatar there. I click on Save, but when I open the saved page directly from the site’s interface, and not the admin panel, the avatar is not there. And it appears there only after some time. What action leads to it appearance on the wiki page, I did not understand.

**Comment by impworks** [comment]
Looks like an issue with VM caching. However, I am unable to reproduce it so far.

**Comment by Katarn** [comment]
This avatar is only missing from the wiki page. But it is present, for example, in a tree, as in all other places of the interface.

**Comment by impworks** [comment]
Please check the following:

1. Does the page show no avatar at all (A), or displays a broken image with a missing source (B)?
2. If A: does the file exist in the `media` folder? Are there files with the same name but different size suffixes?
3. If B, does the issue still persist after you restart Bonsai?

**Comment by Katarn** [comment]
> Does the page show no avatar at all (A), or displays a broken image with a missing source (B)?

A. Dysplays "No media", also in HTML template no ".profile-photo" div.

> If A: does the issue still persist after you restart Bonsai?

No, after restart Bonsai container, image is appears on person/event/etc page.

**Comment by impworks** [comment]
Have you tried running the app from Visual Studio? Does it reproduce there as well, or in the docker environment only?

**Comment by Katarn** [comment]
No, I have not tried it. I am a Linux user and very far from .Net development. You can add logging, I can collect logs (preferably, of course, anonymized).

**Comment by Katarn** [comment]
I found that if you just save any connection of any person (even without changing anything) - avatars appear on the pages of biographies.

**Comment by impworks** [comment]
Found and (probably) fixed a cache invalidation bug. Please check the latest version?

**Comment by Katarn** [comment]
Yes, now it works correctly. Thanks!
