### ISSUE TITLE
Customizable tree renderer thoroughness

### ISSUE THREAD

**Issue by impworks** [impworks/bonsai#98]
Bigger value = better looking graph but longer rendering.

For 50 people:
Thoroughness 10 = 0.1 seconds, borderline illegible graph
Thoroughness 400 = 10 seconds, OK graph with a few messy spots
Thoroughness 10000 = 50 seconds, nice clear graph

So, the plan is:
- [ ] Set default to at least 1000
- [ ] Add a configuration option to admin panel to set thoroughness (predefined values in range 300 .. 10000)
- [ ] Reset all graphs on property update

**Comment by impworks** [comment]
Should be done together with #99.

**Comment by centralhardware** [comment]
You can redraw the tree without waiting for the first opening

**Comment by impworks** [comment]
@centralhardware the rendering starts immediately in background after any page/relation is updated. It is not tied to viewing the page in any way.
